spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alibaba-cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.1:8848
server:
  port: 8084
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: orderApp
  clientSecret: 123456
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/august.jks
    secret: august
    alias: august
    password: august