spring:
  application:
    name: @artifactId@
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL-HOST:alibaba-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:alibaba-cloud}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${MYSQL-USER:root}
    password: ${MYSQL-PWD:1234}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS-HOST:alibaba-register}:${NACOS-PORT:8848}
server:
  port: 8084
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: orderApp
  clientSecret: 123456
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/august.jks
    secret: august
    alias: august
    password: august